#!/bin/bash
echo "Starting SnapRAID operation: CHECK..."
date +"%d.%m.%Y %k:%M:%S %Z" > /var/log/snapraid/laststart
echo 'snapraid -l "/var/log/snapraid/snapraid-check-%D-%T.log" check >/var/log/snapraid/snaplog 2>&1' > /var/log/snapraid/lastcmd
nohup snapraid -l "/var/log/snapraid/snapraid-check-%D-%T.log" check >/var/log/snapraid/snaplog 2>&1 & 
sleep 1
