#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
[ -z "$1" ] && exit 1
BOOT="/boot/config/plugins/dwsnap"
echo "Deleting an existing SnapRAID array..."

rm -rf $BOOT/config/"$1"*
rm -rf /var/lib/snapraid/logs/"$1"*
rm -rf /var/lib/snapraid/logs/"$1"

sed -i "s/SELARRAY=.*/SELARRAY=\"primary\"/g" $BOOT/dwsnap.cfg

/usr/local/emhttp/plugins/dwsnap/scripts/write_config >/dev/null 2>&1
