#!/bin/bash
echo "Starting SnapRAID operation: DUP..."
date +"%d.%m.%Y %k:%M:%S %Z" > /var/log/snapraid/laststart
echo 'snapraid -l "/var/log/snapraid/snapraid-dup-%D-%T.log" dup >/var/log/snapraid/snaplog 2>&1' > /var/log/snapraid/lastcmd
(nohup snapraid -l "/var/log/snapraid/snapraid-dup-%D-%T.log" dup >/var/log/snapraid/snaplog 2>&1) & 
sleep 1
