#!/bin/bash
echo "Starting SnapRAID operation: FIX..."
echo 'snapraid -l "/var/log/snapraid/snapraid-fix-%D-%T.log" fix >/var/log/snapraid/snaplog 2>&1' > /var/log/snapraid/lastcmd
(nohup snapraid -l "/var/log/snapraid/snapraid-fix-%D-%T.log" fix >/var/log/snapraid/snaplog 2>&1) & 
