#!/bin/bash
echo "Starting SnapRAID operation: FIX ERRORS..."
echo 'snapraid -l "/var/log/snapraid/snapraid-efix-%D-%T.log" -e fix >/var/log/snapraid/snaplog 2>&1' > /var/log/snapraid/lastcmd
(nohup snapraid -l "/var/log/snapraid/snapraid-efix-%D-%T.log" -e fix >/var/log/snapraid/snaplog 2>&1) & 
sleep 3
