#!/bin/bash
echo "Starting SnapRAID operation: FIX MISSING..."
date +"%d.%m.%Y %k:%M:%S %Z" > /var/log/snapraid/laststart
echo 'snapraid -l "/var/log/snapraid/snapraid-mfix-%D-%T.log" -m fix >/var/log/snapraid/snaplog 2>&1' > /var/log/snapraid/lastcmd
nohup snapraid -l "/var/log/snapraid/snapraid-mfix-%D-%T.log" -m fix >/var/log/snapraid/snaplog 2>&1 & 
sleep 1
