#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
echo "Recreating RAM disk..."

rm -rf /var/lib/snapraid/* 2>&1 | logger -t "snapraid-ramdisk"
sleep 1

umount -l /var/lib/snapraid 2>&1 | logger -t "snapraid-ramdisk"
sleep 1

rm -rf /var/lib/snapraid 2>&1 | logger -t "snapraid-ramdisk"
mkdir -p /var/lib/snapraid 2>&1 | logger -t "snapraid-ramdisk"

mount -t tmpfs -o size=30% tmpfs /var/lib/snapraid 2>&1 | logger -t "snapraid-ramdisk"
sleep 1

chown root:root /var/lib/snapraid 2>&1 | logger -t "snapraid-ramdisk"
chmod 755 /var/lib/snapraid 2>&1 | logger -t "snapraid-ramdisk"

mkdir -p /var/lib/snapraid/logs 2>&1 | logger -t "snapraid-ramdisk"
