#!/bin/bash
echo "Killing all running SnapRAID instances..."
killall snapraid
killall snapraid-runner
killall snapraid-cron
sleep 5
killall -s9 snapraid
killall -s9 snapraid-runner
killall -s9 snapraid-cron
sleep 3
