#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright desertwitch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
echo "Killing all running SnapRAID instances..."
killall snapraid-runner
killall snapraid-cron
killall snapraid
sleep 5
killall -s9 snapraid
killall -s9 snapraid-runner
killall -s9 snapraid-cron
sleep 1
