#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
echo "Killing all running SnapRAID instances..."
killall snapraid-runner
killall snapraid-cron
killall snapraid
sleep 5
if killall -9 snapraid >/dev/null 2>&1; then
    sleep 5
fi
killall -9 snapraid-runner
killall -9 snapraid-cron
sleep 1
