#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
echo "Migrating the previous configuration layout..."
echo "Migrating the previous configuration layout..." | logger -t "snapraid-plugin"

mkdir -p /boot/config/plugins/dwsnap/config
source /boot/config/plugins/dwsnap/dwsnap.cfg

rm -f /tmp/snapmigration
rm -f /etc/snapraid.conf

mv -f /var/lib/snapraid/logs/snaplog /var/lib/snapraid/logs/primary-snaplog
mv -f /var/lib/snapraid/logs/laststart /var/lib/snapraid/logs/primary-laststart
mv -f /var/lib/snapraid/logs/lastfinish /var/lib/snapraid/logs/primary-lastfinish

mv -f /boot/config/plugins/dwsnap/config/lastsync /boot/config/plugins/dwsnap/config/primary-lastsync
mv -f /boot/config/plugins/dwsnap/config/lastscrub /boot/config/plugins/dwsnap/config/primary-lastscrub
mv -f /boot/config/plugins/dwsnap/config/lastnodiff /boot/config/plugins/dwsnap/config/primary-lastnodiff
mv -f /boot/config/plugins/dwsnap/config/syncneeded /boot/config/plugins/dwsnap/config/primary-syncneeded

mv -f /boot/config/plugins/dwsnap/config/snapraid.conf /boot/config/plugins/dwsnap/config/primary.conf
cp -f /usr/local/emhttp/plugins/dwsnap/defaults/primary.cfg /boot/config/plugins/dwsnap/config/primary.cfg
cp -f /usr/local/emhttp/plugins/dwsnap/default.cfg /boot/config/plugins/dwsnap/dwsnap.cfg

[ -n "${PRIO}" ] && sed -i "s/PRIO=.*/PRIO=\"${PRIO}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${SYNCEXPIRES}" ] && sed -i "s/SYNCEXPIRES=.*/SYNCEXPIRES=\"${SYNCEXPIRES}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${SCRUBEXPIRES}" ] && sed -i "s/SCRUBEXPIRES=.*/SCRUBEXPIRES=\"${SCRUBEXPIRES}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${RAWREPORTS}" ] && sed -i "s/RAWREPORTS=.*/RAWREPORTS=\"${RAWREPORTS}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${MANDISCERRS}" ] && sed -i "s/MANDISCERRS=.*/MANDISCERRS=\"${MANDISCERRS}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${MAINDISCERRS}" ] && sed -i "s/MAINDISCERRS=.*/MAINDISCERRS=\"${MAINDISCERRS}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${CRON}" ] && sed -i "s/CRON=.*/CRON=\"${CRON}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${CRONHOUR}" ] && sed -i "s/CRONHOUR=.*/CRONHOUR=\"${CRONHOUR}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${CRONDOW}" ] && sed -i "s/CRONDOW=.*/CRONDOW=\"${CRONDOW}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${CRONDOM}" ] && sed -i "s/CRONDOM=.*/CRONDOM=\"${CRONDOM}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${STARTNOTIFY}" ] && sed -i "s/STARTNOTIFY=.*/STARTNOTIFY=\"${STARTNOTIFY}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${FINISHNOTIFY}" ] && sed -i "s/FINISHNOTIFY=.*/FINISHNOTIFY=\"${FINISHNOTIFY}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${ERRORNOTIFY}" ] && sed -i "s/ERRORNOTIFY=.*/ERRORNOTIFY=\"${ERRORNOTIFY}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${HEALTHCHECK}" ] && sed -i "s/HEALTHCHECK=.*/HEALTHCHECK=\"${HEALTHCHECK}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${HEALTHCHECKUUID}" ] && sed -i "s/HEALTHCHECKUUID=.*/HEALTHCHECKUUID=\"${HEALTHCHECKUUID}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${NOPROGRESS}" ] && sed -i "s/NOPROGRESS=.*/NOPROGRESS=\"${NOPROGRESS}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${TOUCH}" ] && sed -i "s/TOUCH=.*/TOUCH=\"${TOUCH}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${TOUCHNODIFFS}" ] && sed -i "s/TOUCHNODIFFS=.*/TOUCHNODIFFS=\"${TOUCHNODIFFS}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${DIFF}" ] && sed -i "s/DIFF=.*/DIFF=\"${DIFF}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${SYNC}" ] && sed -i "s/SYNC=.*/SYNC=\"${SYNC}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${SYNCNODIFFS}" ] && sed -i "s/SYNCNODIFFS=.*/SYNCNODIFFS=\"${SYNCNODIFFS}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${PREHASH}" ] && sed -i "s/PREHASH=.*/PREHASH=\"${PREHASH}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${FORCEZERO}" ] && sed -i "s/FORCEZERO=.*/FORCEZERO=\"${FORCEZERO}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${SYNCERRORS}" ] && sed -i "s/SYNCERRORS=.*/SYNCERRORS=\"${SYNCERRORS}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${SCRUB}" ] && sed -i "s/SCRUB=.*/SCRUB=\"${SCRUB}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${SCRUBPERCENT}" ] && sed -i "s/SCRUBPERCENT=.*/SCRUBPERCENT=\"${SCRUBPERCENT}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${SCRUBAGE}" ] && sed -i "s/SCRUBAGE=.*/SCRUBAGE=\"${SCRUBAGE}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${SCRUBNEW}" ] && sed -i "s/SCRUBNEW=.*/SCRUBNEW=\"${SCRUBNEW}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${SCRUBERRORS}" ] && sed -i "s/SCRUBERRORS=.*/SCRUBERRORS=\"${SCRUBERRORS}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${ADDED}" ] && sed -i "s/ADDED=.*/ADDED=\"${ADDED}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${DELETED}" ] && sed -i "s/DELETED=.*/DELETED=\"${DELETED}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${UPDATED}" ] && sed -i "s/UPDATED=.*/UPDATED=\"${UPDATED}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${MOVED}" ] && sed -i "s/MOVED=.*/MOVED=\"${MOVED}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${COPIED}" ] && sed -i "s/COPIED=.*/COPIED=\"${COPIED}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg
[ -n "${RESTORED}" ] && sed -i "s/RESTORED=.*/RESTORED=\"${RESTORED}\"/g" /boot/config/plugins/dwsnap/config/primary.cfg

[ -n "${DASHBOARDS}" ] && sed -i "s/DASHBOARDS=.*/DASHBOARDS=\"${DASHBOARDS}\"/g" /boot/config/plugins/dwsnap/dwsnap.cfg
[ -n "${FOOTER}" ] && sed -i "s/FOOTER=.*/FOOTER=\"${FOOTER}\"/g" /boot/config/plugins/dwsnap/dwsnap.cfg
[ -n "${SCREENIMG}" ] && sed -i "s/SCREENIMG=.*/SCREENIMG=\"${SCREENIMG}\"/g" /boot/config/plugins/dwsnap/dwsnap.cfg
[ -n "${STOPARRAY}" ] && sed -i "s/STOPARRAY=.*/STOPARRAY=\"${STOPARRAY}\"/g" /boot/config/plugins/dwsnap/dwsnap.cfg
[ -n "${KILLTIME}" ] && sed -i "s/KILLTIME=.*/KILLTIME=\"${KILLTIME}\"/g" /boot/config/plugins/dwsnap/dwsnap.cfg
