#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright desertwitch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
echo "Resetting SnapRAID configuration..."

if [ -f /boot/config/plugins/dynamix/dwsnap-maintenance.cron ]; then
    rm -f /boot/config/plugins/dynamix/dwsnap-maintenance.cron
    sleep 1
    update_cron
    sleep 1
fi

rm -f /etc/snapraid.conf
rm -f /boot/config/plugins/dwsnap/dwsnap.cfg
rm -rf /boot/config/plugins/dwsnap/config
rm -rf /var/lib/snapraid/logs

BOOT="/boot/config/plugins/dwsnap"
DOCROOT="/usr/local/emhttp/plugins/dwsnap"

if [ ! -d $BOOT/config ]; then
    mkdir -p $BOOT/config
fi

if [ ! -d /var/lib/snapraid/logs ]; then
    mkdir -p /var/lib/snapraid/logs
fi

cp -f $DOCROOT/default.cfg $BOOT/dwsnap.cfg
cp -f $DOCROOT/defaults/snapraid.conf $BOOT/config/snapraid.conf

if [ ! -L /etc/snapraid.conf ]; then
    rm -f /etc/snapraid.conf
    ln -sf $BOOT/config/snapraid.conf /etc/snapraid.conf
fi


