#!/bin/bash
echo "Starting SnapRAID operation: SCRUB..."
echo 'snapraid -l "/var/log/snapraid/snapraid-scrub-%D-%T.log" scrub >/var/log/snapraid/snaplog 2>&1' > /var/log/snapraid/lastcmd
(nohup snapraid -l "/var/log/snapraid/snapraid-scrub-%D-%T.log" scrub >/var/log/snapraid/snaplog 2>&1) & 
