#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright desertwitch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#

CONFIG="/boot/config/plugins/dwsnap/dwsnap.cfg"
[ -e "$CONFIG" ] && source $CONFIG

if [ -z "$KILLTIME" ] || [[ ! $KILLTIME =~ ^[0-9]+$ ]]; then
    KILLTIME="30"
fi

WASRUNNING="NO"

if pgrep -x snapraid >/dev/null 2>&1 || pgrep -x snapraid-cron >/dev/null 2>&1 || pgrep -x snapraid-runner >/dev/null 2>&1; then
    WASRUNNING="YES"
    echo "Now attempting to stop running SnapRAID instance..." | logger -t "snapraid-shutdown"
    killall snapraid-runner
    killall snapraid-cron
    killall snapraid
    sleep 5
fi

if pgrep -x snapraid >/dev/null 2>&1 || pgrep -x snapraid-cron >/dev/null 2>&1 || pgrep -x snapraid-runner >/dev/null 2>&1; then
    WASRUNNING="YES"
    if pgrep -x snapraid >/dev/null 2>&1; then
        WASRUNNING="YES"
        echo "WARNING: Shutting down hanging 'snapraid' instance..." | logger -t "snapraid-shutdown"
        TIMER=0
        while killall snapraid 2>/dev/null; do
            sleep 1
            killall snapraid-runner
            killall snapraid-cron
            killall snapraid
            TIMER=$((TIMER+1))
            if [ $TIMER -ge "$KILLTIME" ]; then
                echo "ERROR: Hard-killing hanging 'snapraid' instance after ${KILLTIME} seconds..." | logger -t "snapraid-shutdown"
                if killall -9 snapraid >/dev/null 2>&1; then
                    sleep 5
                fi
                killall -9 snapraid-runner
                killall -9 snapraid-cron
                break
            fi
        done
    fi

    if pgrep -x snapraid-runner >/dev/null 2>&1; then
        WASRUNNING="YES"
        echo "WARNING: Shutting down hanging 'snapraid-runner' instance..." | logger -t "snapraid-shutdown"
        TIMER=0
        while killall snapraid-runner 2>/dev/null; do
            sleep 1
            killall snapraid-runner
            killall snapraid-cron
            killall snapraid
            TIMER=$((TIMER+1))
            if [ $TIMER -ge "$KILLTIME" ]; then
                echo "ERROR: Hard-killing hanging 'snapraid-runner' instance after ${KILLTIME} seconds..." | logger -t "snapraid-shutdown"
                if killall -9 snapraid >/dev/null 2>&1; then
                    sleep 5
                fi
                killall -9 snapraid-runner
                killall -9 snapraid-cron
                break
            fi
        done
    fi

    if pgrep -x snapraid-cron >/dev/null 2>&1; then
        WASRUNNING="YES"
        echo "WARNING: Shutting down hanging 'snapraid-cron' instance..." | logger -t "snapraid-shutdown"
        TIMER=0
        while killall snapraid-cron 2>/dev/null; do
            sleep 1
            killall snapraid-runner
            killall snapraid-cron
            killall snapraid
            TIMER=$((TIMER+1))
            if [ $TIMER -ge "$KILLTIME" ]; then
                echo "ERROR: Hard-killing hanging 'snapraid-cron' instance after ${KILLTIME} seconds..." | logger -t "snapraid-shutdown"
                if killall -9 snapraid >/dev/null 2>&1; then
                    sleep 5
                fi
                killall -9 snapraid-runner
                killall -9 snapraid-cron
                break
            fi
        done
    fi
fi

if [ "$1" != "nobackup" ]; then
    if [ "$WASRUNNING" == "YES" ]; then
        if [ -f /var/lib/snapraid/logs/snaplog ]; then
            echo "Backing up SNAPLOG to USB drive..." | logger -t "snapraid-shutdown"
            cp -f /var/lib/snapraid/logs/snaplog /boot/config/plugins/dwsnap/config/snaplog
            echo "This operation output was saved because it seems to have been running when the system shutdown." >> /boot/config/plugins/dwsnap/config/snaplog
        fi
    else
        if [ -f /boot/config/plugins/dwsnap/config/snaplog ]; then
            echo "Removing outdated SNAPLOG from USB drive..." | logger -t "snapraid-shutdown"
            rm -f /boot/config/plugins/dwsnap/config/snaplog
        fi
    fi
fi
