#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright desertwitch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
WASRUNNING="NO"

if pgrep -x snapraid >/dev/null 2>&1 || pgrep -x snapraid-cron >/dev/null 2>&1 || pgrep -x snapraid-runner >/dev/null 2>&1; then
    WASRUNNING="YES"
    echo "Now attempting to stop any running SnapRAID services..." | logger -t "snapraid-plugin"
    killall snapraid-runner
    killall snapraid-cron
    killall snapraid
    sleep 5
fi

if pgrep -x snapraid >/dev/null 2>&1 || pgrep -x snapraid-cron >/dev/null 2>&1 || pgrep -x snapraid-runner >/dev/null 2>&1; then
    WASRUNNING="YES"
    if pgrep -x snapraid >/dev/null 2>&1; then
        WASRUNNING="YES"
        echo "WARNING: Shutting down hanging 'snapraid' instance..." | logger -t "snapraid"
        TIMER=0
        while killall snapraid 2>/dev/null; do
            sleep 1
            killall snapraid-runner
            killall snapraid-cron
            killall snapraid
            TIMER=$((TIMER+1))
            if [ $TIMER -ge 10 ]; then
                echo "ERROR: Hard-killing hanging 'snapraid' instance..." | logger -t "snapraid-plugin"
                killall -9 snapraid-runner
                killall -9 snapraid-cron
                killall -9 snapraid
                sleep 1
                break
            fi
        done
    fi

    if pgrep -x snapraid-runner >/dev/null 2>&1; then
        WASRUNNING="YES"
        echo "WARNING: Shutting down hanging 'snapraid-runner' instance..." | logger -t "snapraid-plugin"
        TIMER=0
        while killall snapraid-runner 2>/dev/null; do
            sleep 1
            killall snapraid-runner
            killall snapraid-cron
            killall snapraid
            TIMER=$((TIMER+1))
            if [ $TIMER -ge 5 ]; then
                echo "ERROR: Hard-killing hanging 'snapraid-runner' instance..." | logger -t "snapraid-plugin"
                killall -9 snapraid-runner
                killall -9 snapraid-cron
                killall -9 snapraid
                sleep 1
                break
            fi
        done
    fi

    if pgrep -x snapraid-cron >/dev/null 2>&1; then
        WASRUNNING="YES"
        echo "WARNING: Shutting down hanging 'snapraid-cron' instance..." | logger -t "snapraid-plugin"
        TIMER=0
        while killall snapraid-cron 2>/dev/null; do
            sleep 1
            killall snapraid-runner
            killall snapraid-cron
            killall snapraid
            TIMER=$((TIMER+1))
            if [ $TIMER -ge 5 ]; then
                echo "ERROR: Hard-killing hanging 'snapraid-cron' instance..." | logger -t "snapraid-plugin"
                killall -9 snapraid-runner
                killall -9 snapraid-cron
                killall -9 snapraid
                sleep 1
                break
            fi
        done
    fi
fi

if [ "$WASRUNNING" == "YES" ] && [ -f /var/lib/snapraid/logs/snaplog ]; then
    cp -f /var/lib/snapraid/logs/snaplog /boot/config/plugins/dwsnap/config/snaplog
    echo "This operation file was backed up possibly being the last log file before system shutdown." >> /boot/config/plugins/dwsnap/config/snaplog
else
    [ -f /boot/config/plugins/dwsnap/config/snaplog ] && rm -f /boot/config/plugins/dwsnap/config/snaplog
fi
