#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
CONFIG="/boot/config/plugins/dwsnap/dwsnap.cfg"
[ -e "$CONFIG" ] && source $CONFIG

if [ -z "$KILLTIME" ] || [[ ! $KILLTIME =~ ^[0-9]+$ ]]; then
    KILLTIME="30"
fi

WASRUNNING="NO"

if pgrep -x snapraid >/dev/null 2>&1 || pgrep -x snapraid-cron >/dev/null 2>&1 || pgrep -x snapraid-runner >/dev/null 2>&1; then
    WASRUNNING="YES"
    echo "Now attempting to stop running SnapRAID instance (${KILLTIME}s)..."
    echo "[warning] Now attempting to stop running SnapRAID instance (${KILLTIME}s)..." | logger -t "snapraid-plugin"
    killall snapraid-runner
    killall snapraid-cron
    killall snapraid
    sleep 5
fi

if pgrep -x snapraid >/dev/null 2>&1 || pgrep -x snapraid-cron >/dev/null 2>&1 || pgrep -x snapraid-runner >/dev/null 2>&1; then
    WASRUNNING="YES"
    if pgrep -x snapraid >/dev/null 2>&1; then
        WASRUNNING="YES"
        echo "[warning] Still shutting down a 'snapraid' instance..." | logger -t "snapraid-plugin"
        TIMER=0
        while killall snapraid >/dev/null 2>&1; do
            sleep 1
            killall snapraid-runner
            killall snapraid-cron
            killall snapraid
            TIMER=$((TIMER+1))
            if [ $TIMER -ge "$KILLTIME" ]; then
                echo "[error] Hard-killing hanging 'snapraid' instance after ${KILLTIME} seconds..." | logger -t "snapraid-plugin"
                if killall -9 snapraid >/dev/null 2>&1; then
                    sleep 5
                fi
                killall -9 snapraid-runner
                killall -9 snapraid-cron
                break
            fi
        done
    fi

    if pgrep -x snapraid-runner >/dev/null 2>&1; then
        WASRUNNING="YES"
        echo "[warning] Still shutting down a 'snapraid-runner' instance..." | logger -t "snapraid-plugin"
        TIMER=0
        while killall snapraid-runner >/dev/null 2>&1; do
            sleep 1
            killall snapraid-runner
            killall snapraid-cron
            killall snapraid
            TIMER=$((TIMER+1))
            if [ $TIMER -ge "$KILLTIME" ]; then
                echo "[error] Hard-killing hanging 'snapraid-runner' instance after ${KILLTIME} seconds..." | logger -t "snapraid-plugin"
                if killall -9 snapraid >/dev/null 2>&1; then
                    sleep 5
                fi
                killall -9 snapraid-runner
                killall -9 snapraid-cron
                break
            fi
        done
    fi

    if pgrep -x snapraid-cron >/dev/null 2>&1; then
        WASRUNNING="YES"
        echo "[warning] Still shutting down a 'snapraid-cron' instance..." | logger -t "snapraid-plugin"
        TIMER=0
        while killall snapraid-cron >/dev/null 2>&1; do
            sleep 1
            killall snapraid-runner
            killall snapraid-cron
            killall snapraid
            TIMER=$((TIMER+1))
            if [ $TIMER -ge "$KILLTIME" ]; then
                echo "[error] Hard-killing hanging 'snapraid-cron' instance after ${KILLTIME} seconds..." | logger -t "snapraid-plugin"
                if killall -9 snapraid >/dev/null 2>&1; then
                    sleep 5
                fi
                killall -9 snapraid-runner
                killall -9 snapraid-cron
                break
            fi
        done
    fi
fi

if [ "$1" != "nobackup" ]; then
    if [ "$WASRUNNING" == "YES" ]; then
        for logfile in /var/lib/snapraid/logs/*-snaplog; do
            logname=$(basename "$logfile")
            echo "[warning] Backing up SNAPLOG to USB drive... ${logfile}" | logger -t "snapraid-plugin"
            cp -f "$logfile" "/boot/config/plugins/dwsnap/config/${logname}"
            echo "This operation output was saved because it may have been running when the system shutdown." >> "/boot/config/plugins/dwsnap/config/${logname}"
        done
    else
        rm -f /boot/config/plugins/dwsnap/config/*-snaplog
    fi
fi
