#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright desertwitch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
BIGOP="$(echo "$1" | awk '{print toupper($0)}')"
[ -n "$2" ] && BIGOP="$(echo "$1 $2" | awk '{print toupper($0)}')"
echo "Starting SnapRAID operation: $BIGOP..."
if [ -n "$2" ]; then
    nohup /usr/bin/snapraid-runner "$1" "$2" >/dev/null 2>&1 &
else
    nohup /usr/bin/snapraid-runner "$1" >/dev/null 2>&1 &
fi
sleep 1
