#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
params=("$@")
for i in "${!params[@]}"; do [ -z "${params[i]}" ] && unset "params[i]"; done
BIGOP="$(echo "$1" | awk '{print toupper($0)}')"
echo "Starting SnapRAID operation: $BIGOP..."
nohup /usr/bin/snapraid-runner "${params[@]}" >/dev/null 2>&1 &
sleep 1
