#!/bin/bash
echo "Starting SnapRAID operation: SYNC..."
echo 'snapraid -l "/var/log/snapraid/snapraid-sync-%D-%T.log" sync >/var/log/snapraid/snaplog 2>&1' > /var/log/snapraid/lastcmd
(nohup snapraid -l "/var/log/snapraid/snapraid-sync-%D-%T.log" sync >/var/log/snapraid/snaplog 2>&1) & 
sleep 3
