#!/bin/bash
echo "Starting SnapRAID operation: TOUCH..."
echo 'snapraid -l "/var/log/snapraid-touch-%D-%T.log" touch >/var/log/snapraid/snaplog 2>&1' > /var/log/snapraid/lastcmd
(nohup snapraid -l "/var/log/snapraid-touch-%D-%T.log" touch >/var/log/snapraid/snaplog 2>&1) & 
