#!/bin/bash
DOCROOT="/usr/local/emhttp/plugins/dwsnap"
CONFIG="/boot/config/plugins/dwsnap/dwsnap.cfg"
[ -e "$CONFIG" ] && source $CONFIG

echo "Initiating SnapRAID configuration..."

if [ "$CRON" == "hourly" ]; then
    cp -f $DOCROOT/misc/dwsnap-maintenance.cron /boot/config/plugins/dynamix/dwsnap-maintenance.cron
    sed -i '/snapraid-cron/s,^\*,0,' /boot/config/plugins/dynamix/dwsnap-maintenance.cron
elif [ "$CRON" == "daily" ]; then
    cp -f $DOCROOT/misc/dwsnap-maintenance.cron /boot/config/plugins/dynamix/dwsnap-maintenance.cron
    sed -i "/snapraid-cron/s,^\* \*,0 ${CRONHOUR}," /boot/config/plugins/dynamix/dwsnap-maintenance.cron
elif [ "$CRON" == "weekly" ]; then
    cp -f $DOCROOT/misc/dwsnap-maintenance.cron /boot/config/plugins/dynamix/dwsnap-maintenance.cron
    sed -i "/snapraid-cron/s,^\* \* \* \* \*,0 ${CRONHOUR} \* \* ${CRONDOW}," /boot/config/plugins/dynamix/dwsnap-maintenance.cron
elif [ "$CRON" == "monthly" ]; then
    cp -f $DOCROOT/misc/dwsnap-maintenance.cron /boot/config/plugins/dynamix/dwsnap-maintenance.cron
    sed -i "/snapraid-cron/s,^\* \* \*,0 ${CRONHOUR} ${CRONDOM}," /boot/config/plugins/dynamix/dwsnap-maintenance.cron
else
    rm -f /boot/config/plugins/dynamix/dwsnap-maintenance.cron
fi

sleep 1
update_cron
sleep 1
