#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
DOCROOT="/usr/local/emhttp/plugins/dwsnap"
CONFIG="/boot/config/plugins/dwsnap/dwsnap.cfg"
[ -e "$CONFIG" ] && source $CONFIG

echo "Initiating SnapRAID configuration..."

if [ "$( grep -ic "dwsnap" /etc/rc.d/rc.local_shutdown )" -eq 0 ]; then
    sed -i -e '/# Get time-out setting/i [ -x /usr/local/emhttp/plugins/dwsnap/scripts/shutdown ] && /usr/local/emhttp/plugins/dwsnap/scripts/shutdown' -e //N /etc/rc.d/rc.local_shutdown
fi

if [ "$CRON" == "hourly" ]; then
    cp -f $DOCROOT/misc/dwsnap-maintenance.cron /boot/config/plugins/dynamix/dwsnap-maintenance.cron
    sed -i '/snapraid-cron/s,^\*,0,' /boot/config/plugins/dynamix/dwsnap-maintenance.cron
elif [ "$CRON" == "daily" ]; then
    cp -f $DOCROOT/misc/dwsnap-maintenance.cron /boot/config/plugins/dynamix/dwsnap-maintenance.cron
    sed -i "/snapraid-cron/s,^\* \*,0 ${CRONHOUR}," /boot/config/plugins/dynamix/dwsnap-maintenance.cron
elif [ "$CRON" == "weekly" ]; then
    cp -f $DOCROOT/misc/dwsnap-maintenance.cron /boot/config/plugins/dynamix/dwsnap-maintenance.cron
    sed -i "/snapraid-cron/s,^\* \* \* \* \*,0 ${CRONHOUR} \* \* ${CRONDOW}," /boot/config/plugins/dynamix/dwsnap-maintenance.cron
elif [ "$CRON" == "monthly" ]; then
    cp -f $DOCROOT/misc/dwsnap-maintenance.cron /boot/config/plugins/dynamix/dwsnap-maintenance.cron
    sed -i "/snapraid-cron/s,^\* \* \*,0 ${CRONHOUR} ${CRONDOM}," /boot/config/plugins/dynamix/dwsnap-maintenance.cron
else
    rm -f /boot/config/plugins/dynamix/dwsnap-maintenance.cron
fi

sleep 1
update_cron
sleep 1
