#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#

PKGTIME="$(date '+%Y%m%d%H%M%S' 2>/dev/null)"
PKGNAME="snapraid-logs-${PKGTIME}.zip"

rm -f /tmp/snapraid-logs-*.zip
(cd /var/lib/snapraid/logs && zip -R "/tmp/${PKGNAME}" '*.log' 2>&1)
[ -f "/tmp/${PKGNAME}" ] && echo "DONE:/tmp/${PKGNAME}" 2>&1
