#!/bin/bash
if pgrep -x snapraid >/dev/null 2>&1 || pgrep -x snapraid-cron >/dev/null 2>&1 || pgrep -x snapraid-runner >/dev/null 2>&1; then
    echo "Now attempting to stop any running services..." | logger -t "snapraid-plugin"
    killall snapraid
    sleep 5
fi

if pgrep -x snapraid >/dev/null 2>&1; then
    echo "Shutting down hanging 'snapraid' service..." | logger -t "snapraid"
    TIMER=0
    while killall snapraid 2>/dev/null; do
        sleep 1
        killall snapraid
        TIMER=$((TIMER+1))
        if [ $TIMER -ge 10 ]; then
            echo "Hard-killing hanging 'snapraid' service..." | logger -t "snapraid-plugin"
            killall -9 snapraid
            sleep 1
            break
        fi
    done
fi

if pgrep -x snapraid-runner >/dev/null 2>&1; then
    echo "Shutting down hanging 'snapraid-runner' service..." | logger -t "snapraid-plugin"
    TIMER=0
    while killall snapraid-runner 2>/dev/null; do
        sleep 1
        killall snapraid-runner
        TIMER=$((TIMER+1))
        if [ $TIMER -ge 5 ]; then
            echo "Hard-killing hanging 'snapraid-runner' service..." | logger -t "snapraid-plugin"
            killall -9 snapraid-runner
            sleep 1
            break
        fi
    done
fi

if pgrep -x snapraid-cron >/dev/null 2>&1; then
    echo "Shutting down hanging 'snapraid-cron' service..." | logger -t "snapraid-plugin"
    TIMER=0
    while killall snapraid-cron 2>/dev/null; do
        sleep 1
        killall snapraid-cron
        TIMER=$((TIMER+1))
        if [ $TIMER -ge 5 ]; then
            echo "Hard-killing hanging 'snapraid-cron' service..." | logger -t "snapraid-plugin"
            killall -9 snapraid-cron
            sleep 1
            break
        fi
    done
fi
